# Generated by Django 6.0.6 on 2026-07-03 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("adcode", models.CharField(blank=True, max_length=6)),
                (
                    "center_lng",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "center_lat",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("cover_image", models.CharField(blank=True, max_length=500)),
                (
                    "target_style",
                    models.CharField(
                        choices=[
                            ("free", "随性型"),
                            ("planner", "规划型"),
                            ("both", "通用"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gaode_poi_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=10)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("business_hours", models.CharField(blank=True, max_length=200)),
                ("ticket_info", models.CharField(blank=True, max_length=500)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("need_reservation", models.BooleanField(default=False)),
                ("suggested_duration", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_hidden_gem", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pois",
                        to="travel.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="PoiTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("scraped_xhs", "小红书"),
                            ("scraped_mfw", "马蜂窝"),
                            ("ai", "AI生成"),
                        ],
                        default="user",
                        max_length=30,
                    ),
                ),
                ("useful_count", models.IntegerField(default=0)),
                ("show_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="travel.poi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hotel_area", models.CharField(blank=True, max_length=200)),
                (
                    "route_type",
                    models.CharField(
                        choices=[("compact", "紧凑型"), ("flexible", "弹性型")],
                        default="compact",
                        max_length=20,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("drive", "驾车"),
                            ("transit", "公交"),
                            ("mix", "混合"),
                        ],
                        default="drive",
                        max_length=20,
                    ),
                ),
                ("total_days", models.IntegerField(default=1)),
                ("route_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("saved", "已保存"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("share_code", models.CharField(blank=True, max_length=6)),
                ("share_expires_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="travel.city",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PoiCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.poi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("user", "poi")},
            },
        ),
        migrations.CreateModel(
            name="ThemePOI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.poi"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_pois",
                        to="travel.theme",
                    ),
                ),
            ],
            options={
                "unique_together": {("theme", "poi")},
            },
        ),
    ]
